In [2]:
import numpy as np

In [16]:
print(np.pad(np.zeros((8, 8), dtype=int), 1, constant_values=1))

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:
print( np.tile([[0, 1], [1, 0]], (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
print(np.fromfunction(lambda i, j: (i > j) * (i - j), (5, 5), dtype=int))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [2 1 0 0 0]
 [3 2 1 0 0]
 [4 3 2 1 0]]


In [5]:
print((lambda x: x - x.mean(axis=1, keepdims=True))(np.random.rand(5, 5)))

[[-2.17849717e-01  2.61654967e-01  2.34189876e-01 -3.42055193e-01
   6.40600672e-02]
 [-4.09761041e-01  4.29230920e-01  2.02749806e-01  1.65626389e-01
  -3.87846075e-01]
 [-3.40632581e-01  2.09897185e-01  1.73290671e-01  1.73846128e-01
  -2.16401403e-01]
 [-2.56172880e-01  4.42888143e-01 -7.37431630e-02 -2.20020316e-01
   1.07048215e-01]
 [-2.58954851e-01 -3.55371967e-04 -2.20543993e-01  4.93408677e-01
  -1.35544605e-02]]


In [6]:
print((lambda a: a[np.arange(10), np.abs(a - 0.5).argmin(axis=1)])(np.random.rand(10, 3)))

[0.56698988 0.51590526 0.3934846  0.56068711 0.23630031 0.79214687
 0.51393506 0.5691633  0.64750074 0.51213933]


In [9]:
print((lambda a: a.sum(axis=1) / a.max(axis=0))(np.random.rand(6, 6)))

[3.27986668 5.55184659 4.20922428 3.65184729 3.42218986 4.30981416]


In [10]:
print(np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])[1:][np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])[:-1] == 0].max())

5


In [12]:
print(np.ones(10) + np.bincount(np.array([0, 1, 2, 3, 5, 5, 5, 8]), minlength=10))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [13]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]); b = np.array([3, 5, 10, 0]); print(b[np.abs(a[..., None] - b).argmin(axis=-1)])

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


In [14]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]); print(np.convolve(a, np.ones(3)/3, mode='valid'))

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]


In [15]:
a = np.arange(40).reshape(4, 10); print((a[:-1, :-1] + a[1:, :-1] + a[:-1, 1:] + a[1:, 1:]) / 4)

[[ 5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
 [15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5]
 [25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5]]
